<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddCollectionrate extends Migration
{
	private $table = 'col_collection_rate';
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create($this->table, function (Blueprint $table) {
            $table->increments('id');
            $table->integer('col_acct_title_id')->unsigned()->nullable();
            $table->integer('col_acct_subtitle_id')->unsigned()->nullable();
            $table->string('type', 100);
            $table->string('label', 100);
            $table->decimal('value', 10, 3)->nullable();
            $table->boolean('is_shared', 10, 2);
            $table->decimal('sharepct_provincial', 10, 2)->nullable();
            $table->decimal('sharepct_municipal', 10, 2)->nullable();
            $table->decimal('sharepct_barangay', 10, 2)->nullable();
            $table->boolean('sched_is_perunit')->nullable();
            $table->string('sched_unit', 100)->nullable();
            $table->boolean('pct_is_sum_given')->nullable();
            $table->boolean('pct_deadline')->nullable();
            $table->decimal('pct_rate_per_month', 10, 2)->nullable();
            
            $table->index(['id', 'col_acct_title_id', 'col_acct_subtitle_id'], $this->table);
        });
		
		# Insert
        DB::table($this->table)->insert([
            [ # Professional Tax
                'col_acct_title_id' => 1,
                'col_acct_subtitle_id' => null,
				'type' => 'fixed',
				'label' => '',
				'value' => 300.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Tax on Sand, Gravel & Other Quarry Prod.
                'col_acct_title_id' => 4,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Ordinary earth (unprocessed)',
				'value' => 15.00,
                'is_shared' => 1,
                'sharepct_provincial' => 30,
                'sharepct_municipal' => 30,
                'sharepct_barangay' => 40,
                'sched_is_perunit' => 1,
                'sched_unit' => 'cu.m',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Tax on Sand, Gravel & Other Quarry Prod.
                'col_acct_title_id' => 4,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Washed gravel and sand',
				'value' => 22.50,
                'is_shared' => 1,
                'sharepct_provincial' => 30,
                'sharepct_municipal' => 30,
                'sharepct_barangay' => 40,
                'sched_is_perunit' => 1,
                'sched_unit' => 'cu.m',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Tax on Sand, Gravel & Other Quarry Prod.
                'col_acct_title_id' => 4,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Boulders/stones',
				'value' => 22.50,
                'is_shared' => 1,
                'sharepct_provincial' => 30,
                'sharepct_municipal' => 30,
                'sharepct_barangay' => 40,
                'sched_is_perunit' => 1,
                'sched_unit' => 'cu.m',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Tax on Sand, Gravel & Other Quarry Prod.
                'col_acct_title_id' => 4,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Crushed gravel and sand (processed)',
				'value' => 27.50,
                'is_shared' => 1,
                'sharepct_provincial' => 30,
                'sharepct_municipal' => 30,
                'sharepct_barangay' => 40,
                'sched_is_perunit' => 1,
                'sched_unit' => 'cu.m',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Tax on Delivery Trucks & Vans
                'col_acct_title_id' => 5,
                'col_acct_subtitle_id' => null,
				'type' => 'fixed',
				'label' => '',
				'value' => 600,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Amusement Tax
                'col_acct_title_id' => 6,
                'col_acct_subtitle_id' => null,
				'type' => 'percent',
				'label' => '',
				'value' => 10.00,
                'is_shared' => 1,
                'sharepct_provincial' => 50,
                'sharepct_municipal' => 50,
                'sharepct_barangay' => 0,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => 1,
                'pct_deadline' => 0,
                'pct_rate_per_month' => null,
            ],
            [ # Franchise Tax
                'col_acct_title_id' => 7,
                'col_acct_subtitle_id' => null,
				'type' => 'percent',
				'label' => '',
				'value' => 50.00,
                'is_shared' => 0,
                'sharepct_provincial' => 0,
                'sharepct_municipal' => 0,
                'sharepct_barangay' => 0,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => 1,
                'pct_deadline' => 0,
                'pct_rate_per_month' => null,
            ],
            [ # Printing and Publication Tax
                'col_acct_title_id' => 8,
                'col_acct_subtitle_id' => null,
				'type' => 'percent',
				'label' => '',
				'value' => 0.005,
                'is_shared' => 0,
                'sharepct_provincial' => 0,
                'sharepct_municipal' => 0,
                'sharepct_barangay' => 0,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => 1,
                'pct_deadline' => 0,
                'pct_rate_per_month' => null,
            ],
            [ # Other Taxes (Mining Claims)
                'col_acct_title_id' => 9,
                'col_acct_subtitle_id' => null,
				'type' => 'manual',
				'label' => '',
				'value' => null,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Tax Revenue - Fines & Penalties - on Individual (PTR)
                'col_acct_title_id' => 10,
                'col_acct_subtitle_id' => null,
				'type' => 'percent',
				'label' => '',
				'value' => 25.00,
                'is_shared' => 0,
                'sharepct_provincial' => 0,
                'sharepct_municipal' => 0,
                'sharepct_barangay' => 0,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => 0,
                'pct_deadline' => 1,
                'pct_rate_per_month' => 2,
            ],
            [ # Tax Revenue - Fines & Penalties - Property Taxes
                'col_acct_title_id' => 11,
                'col_acct_subtitle_id' => null,
				'type' => 'percent',
				'label' => '',
				'value' => 25.00,
                'is_shared' => 0,
                'sharepct_provincial' => 0,
                'sharepct_municipal' => 0,
                'sharepct_barangay' => 0,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => 0,
                'pct_deadline' => 1,
                'pct_rate_per_month' => 2,
            ],
            [ # Tax Revenue - Fines & Penalties - Real Property Taxes
                'col_acct_title_id' => null,
                'col_acct_subtitle_id' => 1,
				'type' => 'percent',
				'label' => '',
				'value' => 25.00,
                'is_shared' => 0,
                'sharepct_provincial' => 0,
                'sharepct_municipal' => 0,
                'sharepct_barangay' => 0,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => 0,
                'pct_deadline' => 1,
                'pct_rate_per_month' => 2,
            ],
            [ # Tax Revenue - Fines & Penalties - Goods & Services
                'col_acct_title_id' => 12,
                'col_acct_subtitle_id' => null,
				'type' => 'percent',
				'label' => '',
				'value' => 25.00,
                'is_shared' => 0,
                'sharepct_provincial' => 0,
                'sharepct_municipal' => 0,
                'sharepct_barangay' => 0,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => 0,
                'pct_deadline' => 1,
                'pct_rate_per_month' => 2,
            ],
			[ # Permit Fee
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Printing and Publications',
				'value' => 2000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Permit Fee
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Business enjoying a franchise; Cable Antenna Networks and Radio stations; Telephone/Mobile services and such other similar business',
				'value' => 3000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Permit Fee
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Proprietors, lessors or operators of amusement places',
				'value' => 2000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Permit Fee
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Extraction and processing of sand, gravel and other quarry resources',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Permit Fee
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Operators of delivery trucks or vans regardless of the number of trucks or vans',
				'value' => 500.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Annual Permit Fee for every Crusher Plant, Cement Batching Plant, and Asphalt Batching Plant',
				'value' => 50000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Annual Permit Fee for every Screening Plant Provided, however, that if the Screening Plant is integrated or forms part of the Crusher Plant and no by-product shall be separately produced from the Crusher Plant, only a permit fee on the Crusher Plant be imposed.',
				'value' => 20000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Power producer/operator of hydro-electric plant including mini-hydro electric plant',
				'value' => 10000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Commercial banks, insurance companies and other financial institutions for every branch',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Malls/Department Stores/Supermarkets',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Food Franchises (Large Scale)',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Licensed Contractors (General Engineering & Building Contractors)',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Polyclinics,Medical/Dental/Optical Clinics',
				'value' => 200.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Vocational/Driving School/Music/Dancing School',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Private Educational Institution',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Recruitment Agencies/Travel & Tours',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Physical Fitness Gym',
				'value' => 500.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Real Estate Developers',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Computer Center, Internet Café, Computer job & printing',
				'value' => 500.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Dealers/Suppliers of drugs and medicines',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Dealers/Suppliers of Medical and  Laboratory Supplies',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Dealers/Suppliers of Medical and Laboratory Equipment',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Hauling Fee for every truck and other motor vehicle used and operated in hauling quarry materials.',
				'value' => 500.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Permit Fee (ANNUAL FEE)
                'col_acct_title_id' => 18,
                'col_acct_subtitle_id' => null,
				'type' => 'schedule',
				'label' => 'Other businesses not mentioned herein participating in procurement biddings',
				'value' => 1000.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 0,
                'sched_unit' => '',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Fines & Penalties - Service Income
                'col_acct_title_id' => 21,
                'col_acct_subtitle_id' => null,
				'type' => 'percent',
				'label' => '',
				'value' => 25.00,
                'is_shared' => 0,
                'sharepct_provincial' => 0,
                'sharepct_municipal' => 0,
                'sharepct_barangay' => 0,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => 0,
                'pct_deadline' => 1,
                'pct_rate_per_month' => 2,
            ],
			[ # Rent Income - General (Buildings/Lots/Lights & Water)
                'col_acct_title_id' => null,
                'col_acct_subtitle_id' => 2,
				'type' => 'schedule',
				'label' => 'Commercial purposes',
				'value' => 2.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 1,
                'sched_unit' => 'sq.m',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
			[ # Rent Income - General (Buildings/Lots/Lights & Water)
                'col_acct_title_id' => null,
                'col_acct_subtitle_id' => 2,
				'type' => 'schedule',
				'label' => 'Residential purposes',
				'value' => 1.50,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => 1,
                'sched_unit' => 'sq.m',
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
            [ # Fines & Penalties - Business Income
                'col_acct_title_id' => 28,
                'col_acct_subtitle_id' => null,
				'type' => 'percent',
				'label' => '',
				'value' => 25.00,
                'is_shared' => 0,
                'sharepct_provincial' => 0,
                'sharepct_municipal' => 0,
                'sharepct_barangay' => 0,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => 0,
                'pct_deadline' => 1,
                'pct_rate_per_month' => 2,
            ],
            [ # Insurance Premium (BTS)
                'col_acct_title_id' => 42,
                'col_acct_subtitle_id' => null,
				'type' => 'fixed',
				'label' => '',
				'value' => 50.00,
                'is_shared' => 0,
                'sharepct_provincial' => null,
                'sharepct_municipal' => null,
                'sharepct_barangay' => null,
                'sched_is_perunit' => null,
                'sched_unit' => null,
                'pct_is_sum_given' => null,
                'pct_deadline' => null,
                'pct_rate_per_month' => null,
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists($this->table);
    }
}
